version: '3.8'

services:
  postgres:
    container_name: todo-db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: todo-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
